### ISSUE TITLE
are private repos supported ?

### ISSUE THREAD

**Issue by eko24ive** [renfeng/github-punchcard-webextension#1]

**Comment by renfeng** [comment]
Published a new version, 0.4, for both Firefox and Chrome. And, here is the relevant change.

https://github.com/renfeng/github-punchcard/commit/4818fe4fc36850855ec11ecfbaa48dfda713f30a#diff-691e6b25764944db4893329a85f7a08aR10

Can you test and let me know if it works for private repos? Thanks.

**Comment by eko24ive** [comment]
Sure, I'll check it right now!

**Comment by eko24ive** [comment]
I'm still seeing 404 error:
![image](https://user-images.githubusercontent.com/25591824/40721714-02f30c28-6423-11e8-88ce-87e922f6ce98.png)

Is there any debug data/metric I could provide to you?

**Comment by eko24ive** [comment]
If you want to - I could create and empty private repo and add you as collaborator so you could easily debug this issue.

**Comment by renfeng** [comment]
That would be nice. Please do it. Thanks.

**Comment by eko24ive** [comment]
I've sent you invite link

**Comment by renfeng** [comment]
The api url responds with http status 404, and response body

```
{
  "message": "Not Found",
  "documentation_url": "https://developer.github.com/v3/repos/statistics/#get-the-number-of-commits-per-hour-in-each-day"
}
```

> Requests that require authentication will return 404 Not Found - https://developer.github.com/v3/#authentication

**Comment by renfeng** [comment]
This works, https://developer.github.com/v3/auth/#via-oauth-tokens

![image](https://user-images.githubusercontent.com/449029/40725384-e12a1676-6455-11e8-8586-8b7e39f3c34a.png)

Will ask people to create personal access token with minimum required scope, repo - Full control of private repositories, and enter it to access private repo punch card stats.

**Comment by eko24ive** [comment]
Neat! 
This sounds like the same thing https://github.com/buunguyen/octotree does. Please, keep me updated!

**Comment by renfeng** [comment]
Can you test version 0.8?
https://github.com/renfeng/github-punchcard-webextension/tree/v0.8

- Token generation is guided/automated
- Token saved in chrome.storage.sync

The token can be peeked with devtools
1. Open your extension's background page by going to chrome://extensions/ ("Developer mode" needs to be checked to see background pages)

2. Go to the Console tab and type this:

```chrome.storage.sync.get(function(result){console.log(result)})```

Ref. https://stackoverflow.com/questions/11922964/how-do-i-view-the-storage-of-a-chrome-extension-ive-installed/50690804#50690804

**Comment by eko24ive** [comment]
Is your updates published or I have to build the extension on my own?

**Comment by renfeng** [comment]
It's been published. Can you check if you've automatically got the latest version, 0.8?

**Comment by eko24ive** [comment]
It works super awesome, just checked!

**Comment by eko24ive** [comment]
Also, I think it would be better to come up with more "readable" page rather than one single link:
![image](https://user-images.githubusercontent.com/25591824/41045077-4840636a-69b0-11e8-9ddf-8af1184d59fb.png)

As for me - I'd be more comfortable if page told me that as soon as I click on the link, it will open GitHub auth page, and as soon as I enter my password it will automatically generate token and add it into extensions. I think some users could be scared by this magic.

And it would be nice if you write up what exact permissions you request so users wouldn't worry about data you request.

P.S.
I do understand that you probably wanted to ship the fix for private repos ASAP and decided to put those things I wrote above on the low priority which is fine.

**Comment by renfeng** [comment]
Version 1.0 has been publish, and will be available soon.

https://github.com/renfeng/github-punchcard-webextension/commit/72dcef911de4b776a37115f71b808ed5e7072641

# Options page
![image](https://user-images.githubusercontent.com/449029/41109134-d6892672-6aa8-11e8-998a-7ba032f2f996.png)

# The guide
![image](https://user-images.githubusercontent.com/449029/41109099-c1c8a226-6aa8-11e8-9fcb-430a5f747fe6.png)
